// @author zenjiro 18967498922@163.com
// 文件用途 集中维护界面多语言文本

using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Net;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows.Forms;
using Microsoft.Win32;

namespace CaelusApp
{
    internal static class Lang
    {
        public static int Cur;

        private static readonly Dictionary<string, string[]> M = new Dictionary<string, string[]>
        {
            { "nav.tame", new[]{ "反作弊" } },
            { "nav.white", new[]{ "白名单" } },
            { "nav.log", new[]{ "日志" } },
            { "nav.set", new[]{ "设置" } },
            { "nav.about", new[]{ "关于" } },
            { "nav.overview", new[]{ "概览" } },
            { "nav.library", new[]{ "游戏库" } },
            { "nav.policy", new[]{ "优化策略" } },
            { "v15.about.identity", new[]{ "Windows 性能守护" } },
            { "notes.title", new[]{ "版本说明" } },
            { "notes.sub", new[]{ "当前安装版本 {0}" } },
            { "notes.current", new[]{ "当前版本" } },
            { "notes.open", new[]{ "查看版本说明" } },
            { "notes.online", new[]{ "在 GitHub 查看全部" } },
            { "notes.close", new[]{ "关闭" } },
            { "v15.about.update", new[]{ "版本更新" } },
            { "v15.about.update.sub", new[]{ "只读取 GitHub Releases 版本号，不上传设备数据。" } },
            { "v15.restore.title", new[]{ "恢复已记录调度" } },
            { "v15.restore.desc", new[]{ "把 Caelus 改过的东西全部改回去。游戏还开着的话，几秒后可能会被重新接管。" } },
            { "mode.source.global", new[]{ "全局默认" } },
            { "mode.global.title", new[]{ "全局默认模式" } },
            { "mode.global.sub", new[]{ "所有游戏统一使用" } },
            { "mode.policy.active", new[]{ "当前实际行为 · {0}" } },
            { "mode.tray.current", new[]{ "当前模式：{0}（打开面板切换）" } },
            { "mode.pick.standard", new[]{ "稳妥。后台先轻压，一直抢资源的才加码" } },
            { "mode.pick.competitive", new[]{ "最狠。游戏之外能压的立刻全压，开着窗口的也不例外" } },
            { "mode.pick.custom", new[]{ "全按你的开关来，激进功能不会自己打开" } },
            { "set.pqos", new[]{ "不许无故降级" } },
            { "set.pqos.n", new[]{ "系统默认会在你一段时间没碰键鼠后，把前台程序降一档——手柄游戏、看过场动画、挂机刷本正好中招。开这项就不让它降。微软自己也说测性能时该关掉它" } },
            { "set.awake", new[]{ "不熄屏不睡眠" } },
            { "set.awake.n", new[]{ "打游戏期间不让屏幕熄灭、电脑不进睡眠。手柄玩或者看长过场时不会黑屏。游戏退出自动解除" } },
            { "v15.overview.sub", new[]{ "模式从右上角切换。" } },
            { "v15.guard.state", new[]{ "CAELUS 守护状态" } },
            { "v15.effective.mode", new[]{ "实际生效模式" } },
            { "v15.master.short", new[]{ "认出你在玩的游戏就接管，退出后原样还原" } },
            { "v15.tile.game", new[]{ "游戏资源" } },
            { "v15.tile.game.sub", new[]{ "只给真正出画面的游戏进程提速" } },
            { "v15.tile.background", new[]{ "后台边界" } },
            { "v15.tile.background.sub", new[]{ "系统、声音、白名单绝不误伤" } },
            { "v15.tile.environment", new[]{ "电源与调度" } },
            { "v15.tile.environment.sub", new[]{ "电源和调度跟着模式走" } },
            { "v15.library.sub", new[]{ "随便选游戏目录里的哪个 EXE 都行——真正的渲染进程由现场证据（前台全屏 / GPU 占用）选举，选错也没关系。" } },
            { "v15.library.empty", new[]{ "尚未添加游戏\r\n直接去玩也可以：识别到全屏游戏会自动加入" } },
            { "v15.library.add", new[]{ "＋ 添加游戏" } },
            { "v15.library.drop", new[]{ "EXE / LNK / Steam 快捷方式都行，直接拖进窗口也可以。最省心的加法：先把游戏打开进到画面，再点添加——正在出画面的进程会被自动标出并勾选。全屏游戏还会直接自动入库。" } },
            { "scan.title", new[]{ "添加游戏" } },
            { "scan.browse", new[]{ "浏览文件…" } },
            { "scan.running.tag", new[]{ "运行中" } },
            { "scan.renderer.tag", new[]{ "正在出画面 · GPU {0}%" } },
            { "set.light", new[]{ "亮色模式" } },
            { "set.light.n", new[]{ "浅色界面，切换立即生效；默认暗色" } },
            { "scan.busy", new[]{ "正在读取各平台的安装记录…" } },
            { "scan.busy.deep", new[]{ "正在遍历所选目录 大目录会久一点…" } },
            { "scan.count", new[]{ "找到 {0} 个 · 其中 {1} 个尚未加入" } },
            { "scan.none", new[]{ "没有找到已安装的游戏 可以试试深度扫描指定盘符" } },
            { "scan.all", new[]{ "全选" } },
            { "scan.already", new[]{ "已在库中" } },
            { "scan.add.n", new[]{ "添加 {0} 个" } },
            { "scan.deep", new[]{ "深度扫描…" } },
            { "scan.deep.pick", new[]{ "选择要遍历的盘符或目录 用于找出没有安装记录的绿色版游戏" } },
            { "scan.added", new[]{ "已加入 {0} 个游戏" } },
            { "v15.library.running", new[]{ "运行中" } },
            { "v15.library.ready", new[]{ "已就绪" } },
            { "v15.policy.sub", new[]{ "右上角显示当前模式与实际来源。" } },
            { "v15.policy.mode.hint", new[]{ "常规 / 竞技模式会覆盖部分自定义开关；被强制的项会标出来并锁住" } },
            { "v15.policy.core", new[]{ "全模式核心控制" } },
            { "v15.policy.custom", new[]{ "自定义预设细节" } },
            { "v15.policy.extras", new[]{ "会话附加动作 · 所有模式生效" } },
            { "v15.boost.sub", new[]{ "自动认出真正出画面的游戏进程；启动器和游戏平台不会被当成游戏提速" } },
            { "v15.plan.sub", new[]{ "打游戏时切到 Caelus 自建的「Caelus 竞技」电源计划。竞技模式下 CPU 锁 100% 下限、核心不停放、睿频拉满，Win11 的电源滑块一并推到最佳性能；常规模式留降频余量。退出游戏切回你原来的计划，全程不改你自己的方案" } },
            { "v15.notif.sub", new[]{ "打游戏时不弹系统通知，退出自动恢复" } },
            { "v15.hz.sub", new[]{ "打游戏时把屏幕保持在最高刷新率；显示不正常时再关" } },
            { "v15.custom.override", new[]{ "只在自定义模式下由你决定；竞技模式可能强制开启" } },
            { "v15.trim.sub", new[]{ "把被压制程序占的内存挤出来；它们之后要用得重新读盘，默认关闭" } },
            { "def.title", new[]{ "Defender 扫描排除" } },
            { "def.warn.title", new[]{ "这是拿安全换性能" } },
            { "def.warn.body", new[]{ "被排除的目录不再被实时扫描，其中的恶意文件不会被拦截。游戏目录常混有破解版、第三方 mod 和修改器，风险高于普通目录。只排除你信任来源的游戏。" } },
            { "def.state.on", new[]{ "已排除" } },
            { "def.state.off", new[]{ "受保护" } },
            { "def.confirm", new[]{ "确定要把《{0}》的目录排除出 Defender 实时扫描吗？\r\n\r\n{1}\r\n\r\n该目录下的文件将不再被查杀。只有当你确信这个游戏的来源可靠时才继续。" } },
            { "def.notours", new[]{ "这条排除不是 Caelus 添加的（可能是你在 Windows 安全中心手动加的），Caelus 不会去动它。需要取消请到 Windows 安全中心操作。" } },
            { "def.failed", new[]{ "操作失败，系统未接受这次修改（可能被安全策略或第三方杀软阻止）。" } },
            { "def.unavailable", new[]{ "无法读取 Defender 设置：可能未安装、已被第三方杀软接管，或当前权限不足。" } },
            { "def.off", new[]{ "Defender 的实时保护本来就是关的——没有扫描，也就没有开销可省，这个功能暂时帮不上你。以后开回 Defender 再来即可。" } },
            { "def.nogames", new[]{ "游戏库还是空的。先在「游戏库」里添加游戏，这里才会列出可排除的目录。" } },
            { "def.clearall", new[]{ "全部取消排除" } },
            { "def.clearall.none", new[]{ "Caelus 目前没有添加过任何排除项。" } },
            { "def.clearall.done", new[]{ "已取消 {0} 个由 Caelus 添加的排除项（你手工添加的不受影响）。" } },
            { "addon.open", new[]{ "英雄联盟附加层清理" } },
            { "addon.open.sub", new[]{ "删掉 AI 教练、录制这类附加组件，腾出磁盘也少几个后台进程；游戏本体和登录链路不动" } },
            { "addon.title", new[]{ "英雄联盟附加层清理" } },
            { "addon.desc", new[]{ "删的是客户端里的附加组件，不是游戏本体。删完客户端更新时可能会重新下回来。英雄联盟、WeGame 或反作弊在跑的时候不让删。" } },
            { "addon.pick.desc", new[]{ "选择英雄联盟安装目录（含 Game 和 LeagueClient 那一层）" } },
            { "addon.delete", new[]{ "删除附加层" } },
            { "addon.files", new[]{ "{0} 个文件" } },
            { "addon.absent", new[]{ "不存在" } },
            { "addon.hint.pick", new[]{ "选一个英雄联盟安装目录，或者直接把目录拖进上面的框" } },
            { "addon.hint.busy", new[]{ "正在检查…" } },
            { "addon.hint.fail", new[]{ "检查失败" } },
            { "addon.hint.notlol", new[]{ "这个目录不像英雄联盟的安装位置" } },
            { "addon.hint.clean", new[]{ "没有可删的附加层，已经是干净的" } },
            { "addon.hint.blocked", new[]{ "这些程序还在跑，先全部退出：{0}" } },
            { "addon.hint.ready", new[]{ "可删 {0} 项，共 {1}" } },
            { "addon.hint.deleting", new[]{ "正在删除…" } },
            { "addon.hint.done", new[]{ "已删除 {0} 项，腾出 {1}" } },
            { "addon.confirm", new[]{ "确定要删除这个目录下的附加层吗？\r\n\r\n{0}\r\n\r\n删除不可撤销。游戏本体、登录链路和更新器不在删除范围。" } },
            { "def.open", new[]{ "Defender 扫描排除" } },
            { "def.open.sub", new[]{ "逐个游戏目录手动勾选；会降低这些目录的安全防护" } },
            { "gm.idledisable", new[]{ "竞技模式禁用 CPU 空闲状态" } },
            { "gm.idledisable.sub", new[]{ "CPU 核心不再进入空闲状态，唤醒延迟更低；只在竞技模式生效，插电和电池都会生效，会更热更费电。开了之后监控软件和游戏内 OSD 可能把 CPU 利用率显示成 100%——那读的是核心活跃度，不是真的有负载，实际不会卡" } },
            { "gm.visualfx", new[]{ "游戏时降级桌面视觉效果" } },
            { "gm.visualfx.sub", new[]{ "关闭桌面透明与窗口动画，退出后还原（默认关闭）" } },
            { "v15.anticheat.sub", new[]{ "跟游戏模式无关，只管下面列出来的这些反作弊程序。" } },
            { "v14.master", new[]{ "Caelus 智能守护" } },
            { "preset.standard", new[]{ "常规" } },
            { "preset.competitive", new[]{ "竞技" } },
            { "preset.custom", new[]{ "自定义" } },
            { "v14.cpu.topology", new[]{ "CPU 调度拓扑" } },
            { "v14.boost.status", new[]{ "游戏提权状态" } },
            { "v14.boost.disabled", new[]{ "游戏提优已关闭" } },
            { "v14.boost.wait", new[]{ "等游戏画面出来" } },
            { "v14.boost.no.renderer", new[]{ "看到启动器了，还在等游戏本体" } },
            { "v14.boost.applying", new[]{ "正在提速：{0}" } },
            { "v14.boost.verified", new[]{ "已生效：{0}\r\n提速已写进系统并确认" } },
            { "v14.boost.protected", new[]{ "{0}：已被目标反作弊保护，优先级改不动\r\n后台压制、电源与显卡优化照常生效" } },
            { "v14.bg.master", new[]{ "后台调度 · 总开关" } },
            { "v14.bg.master.sub", new[]{ "关掉就完全不碰后台程序。不管开没开，游戏、反作弊、系统核心、别的账户和白名单永远不会被动；竞技模式下连开着窗口的程序也会被压" } },
            { "v14.cpu.adaptive.sub2", new[]{ "游戏绑性能核、后台赶到能效核，核心不够分时自动放弃，不会硬来。自定义模式下同时会把后台压制拉到最重那档。默认关，任何模式都由这个开关说了算" } },
            { "v14.preset.forced", new[]{ "当前预设强制" } },
            { "v14.anticheat.boundary", new[]{ "反作弊只在这里管，不跟着游戏模式走" } },
            { "v14.anticheat.master.sub", new[]{ "只动下面列出的反作弊程序，不会把游戏平台、登录器当成反作弊" } },
            { "v14.cpu.adaptive", new[]{ "严格 CPU 分区" } },
            { "v14.anticheat", new[]{ "反作弊专项" } },
            { "v14.cpu.multigroup", new[]{ "多处理器组 · CPU Sets 跨组调度 · 竞技模式物理核优先" } },
            { "v14.cpu.hybrid", new[]{ "混合架构 · 后台能效核 · 竞技模式性能核优先" } },
            { "v14.cpu.x3d", new[]{ "非对称 L3 / X3D · 游戏大缓存 CCD · 后台隔离到另一 CCD" } },
            { "v14.cpu.generic", new[]{ "{0} 逻辑处理器 · 常规按需升级 · 竞技立即物理核隔离" } },
            { "detect.learned", new[]{ "命中已确认的渲染进程" } },
            { "detect.fullscreen", new[]{ "前台全屏画面（几何证据）" } },
            { "detect.window", new[]{ "所选 EXE 自带前台窗口" } },
            { "detect.gpu", new[]{ "GPU 3D 引擎主导（{0}%）" } },
            { "detect.gpu.pending", new[]{ "窗口化候选，等待 GPU 证据确认" } },
            { "bal.autoadd", new[]{ "检测到全屏游戏《{0}》，已自动加入目标库。不需要的话在游戏库里移除，之后不会再自动加入。" } },

            { "title.noelev", new[]{ "未提权 · 压制类功能无效" } },
            { "title.admin", new[]{ "管理员权限" } },
            { "title.guard", new[]{ "守护中（{0}）" } },
            { "title.idle", new[]{ "待命" } },

            { "btn.pick", new[]{ "＋ 从运行中选择" } },
            { "btn.browse", new[]{ "＋ 浏览 exe…" } },
            { "btn.remove", new[]{ "－ 移除选中" } },

            { "st.off", new[]{ "已关闭" } },
            { "st.mon", new[]{ "监控中，未检测到列表内的游戏" } },
            { "st.armed", new[]{ "已就位《{0}》— 进入对局画面自动接管" } },
            { "st.grace", new[]{ "《{0}》已退出 · {1} 秒宽限中 — 后台已先还原，重进游戏则无缝续接" } },
            { "st.active", new[]{ "激活中（{0}）· 已压制 {1} 个进程" } },
            { "st.boost", new[]{ " · 已提优 {0} · {1}" } },
            { "st.hp", new[]{ "高性能电源" } },
            { "st.pr", new[]{ "电源就绪" } },

            { "tame.toggle", new[]{ "反作弊压制 · 总开关" } },
            { "set.nvmax", new[]{ "NVIDIA 驱动电源 · 最高性能优先" } },
            { "set.nvmax.n", new[]{ "打游戏时显卡保持最高性能不降频，省掉频率爬升那点延迟。笔记本散热差可能适得其反。关掉就恢复原样" } },
            { "set.nv.none", new[]{ "未检测到 NVIDIA 驱动（NVAPI 不可用），此项停用" } },
            { "set.nvfrl", new[]{ "NVIDIA 帧率上限" } },
            { "set.nvfrl.n", new[]{ "在驱动里给游戏限帧：显卡不再硬顶着跑毛刺帧率，帧数更平稳、更凉快更省电。「屏-3」= 屏幕刷新率减 3。选「关」恢复原样" } },
            { "set.nvll", new[]{ "NVIDIA 低延迟 · 预渲染队列压到 1" } },
            { "set.nvll.n", new[]{ "让显卡少攒帧、画完就出。显卡跑满时能明显降低操作延迟；显卡没跑满就没什么用。不动游戏文件、不改画质，关掉恢复原样" } },
            { "frl.off", new[]{ "关" } },
            { "frl.screen", new[]{ "屏-3" } },
            { "dlss.latest", new[]{ "最新" } },
            { "set.nvdlss", new[]{ "DLSS 换新算法" } },
            { "set.nvdlss.n", new[]{ "游戏里开了 DLSS 的话，这项能让它用上 NVIDIA 最新的算法：画面更清楚、锯齿更少，老游戏也能吃到。一般选「最新」，K 画质通常最好。个别游戏不认，选「关」恢复原样" } },
            { "set.nvdlss.old", new[]{ "驱动太老（需要 566.14+），升级后可用" } },
            { "set.nvrebar", new[]{ "ReBAR 强开" } },
            { "set.nvrebar.n", new[]{ "ReBAR 能让 CPU 大口读显存，但 NVIDIA 只给一部分游戏开了。这项给没上名单的游戏也强开：有的游戏帧数真能涨，个别反而掉，同一个游戏开关各玩一局对比就知道。关掉恢复原样。" } },
            { "set.nvrebar.det.on", new[]{ "检测：本机已开启（窗口 {0}）" } },
            { "set.nvrebar.det.off", new[]{ "检测：本机未开启（窗口 {0}），要在 BIOS 里打开才有用" } },
            { "set.nvansel", new[]{ "不让 Ansel 进游戏" } },
            { "set.nvansel.n", new[]{ "Ansel 是 NVIDIA 塞进游戏里的拍照组件，这项不让它加载：少一个占资源的，跟反作弊也少一层摩擦。不影响游戏自带截图。关掉恢复原样" } },
            { "set.nvbatt", new[]{ "电池满血" } },
            { "set.nvbatt.n", new[]{ "笔记本拔了电源，驱动会偷偷把游戏压到 30/60 帧省电。开这项就不压了，插不插电都满血跑，电池掉得更快" } },
            { "sec.gfx.session", new[]{ "全局驱动项 · 打游戏时生效，退出还原" } },
            { "set.nvbg", new[]{ "后台硬限帧" } },
            { "set.nvbg.n", new[]{ "打游戏时，后台挂着的东西——没关的视频网页、双开的客户端——统统被限到 20 帧，不许跟游戏抢显卡。游戏一退就恢复原样；就算 Caelus 崩了，下次启动也会自动还原" } },
            { "sec.amd", new[]{ "AMD 驱动调优 · 实验性" } },
            { "set.amd.none", new[]{ "未检测到 A 卡或驱动太老，这一区不可用" } },
            { "set.alag", new[]{ "Anti-Lag" } },
            { "set.alag.n", new[]{ "AMD 的抗延迟开关：打游戏时自动打开，从点鼠标到画面有反应的延迟更短，操作更跟手。退游戏恢复原设置。实验性，无 A 卡实机验证" } },
            { "set.achill", new[]{ "Chill 限帧" } },
            { "set.achill.n", new[]{ "打游戏时把帧数摁在你选的值上，不让显卡没完没了地硬冲：帧数更稳、温度更低、风扇更安静。「屏-3」= 屏幕刷新率减 3。退游戏恢复原设置" } },
            { "set.aesync", new[]{ "Enhanced Sync" } },
            { "set.aesync.n", new[]{ "画面老是出现上下错开的撕裂就试试它：不锁帧数也能让画面变整齐。个别游戏跟它八字不合，出问题关掉就行" } },
            { "set.aris", new[]{ "RIS 锐化" } },
            { "set.aris.n", new[]{ "打游戏时给画面加一层锐化，看着更清楚扎实。观感见仁见智，默认关" } },
            { "set.acache", new[]{ "着色器缓存重置" } },
            { "set.acache.n", new[]{ "游戏莫名卡顿、画面偶尔闪，可能是显卡缓存坏了。点一下清掉重建，下次进游戏首次加载会慢一点。一次性动作，不改任何设置" } },
            { "amd.cache.btn", new[]{ "立即重置" } },
            { "amd.cache.done", new[]{ "清好了，下次进游戏首次加载会慢一点" } },
            { "amd.cache.fail", new[]{ "没清成：显卡不支持或驱动拒绝" } },
            { "v16.spec.cpu", new[]{ "处理器" } },
            { "v16.spec.gpu", new[]{ "显示适配器" } },
            { "v16.spec.mem", new[]{ "系统内存" } },
            { "v16.spec.hags", new[]{ "硬件加速 GPU 计划" } },
            { "v16.device.hags.on", new[]{ "已开启" } },
            { "v16.device.hags.off", new[]{ "已关闭" } },
            { "v16.device.hags.none", new[]{ "不支持" } },
            { "rep.log.none", new[]{ "日志为空" } },
            { "rep.clear.log", new[]{ "清除日志" } },
            { "rep.clear.ask", new[]{ "清空运行日志？\r\n\r\nCaelus.log 将被清空；已归档的 Caelus.log.old 不受影响。" } },
            { "gm.standby", new[]{ "对局前清理待机内存" } },
            { "gm.standby.sub", new[]{ "开局前把系统攒的缓存内存清一次，内存小的机器会顺一些；32GB 加固态基本无感。只在开局清，打到一半不会突然清" } },
            { "gm.pausewu", new[]{ "对局期间暂停 Windows 更新" } },
            { "gm.pausewu.sub", new[]{ "打游戏时不让 Windows 更新下载安装，免得对局中硬盘和 CPU 突然被占；退出自动恢复，不改系统的更新设置" } },
            { "set.winopt", new[]{ "窗口化游戏优化" } },
            { "set.winopt.n", new[]{ "让窗口化 / 无边框的游戏走更快的显示通道，延迟更低。跟系统的 VRR、Auto HDR 是同一处设置，只改需要的部分，可恢复。重启游戏生效" } },
            { "winopt.failed", new[]{ "窗口化游戏优化没能写入，系统设置保持原样。" } },
            { "set.usbaffinity", new[]{ "USB 控制器中断避让" } },
            { "set.usbaffinity.n", new[]{ "4K / 8K 高回报率鼠标每秒打断 CPU 几千次，全砸在游戏核心上会甩枪掉帧。这项把它们挪去空闲核心。普通鼠标（1000Hz 及以下）基本无感。重启生效，可恢复" } },
            { "set.gmguard", new[]{ "Windows 游戏模式守护" } },
            { "set.gmguard.n", new[]{ "把 Windows 自带的游戏模式拨回开启：它能挡住打游戏时的驱动安装和重启弹窗，常被旧优化教程误关。本来就开着则不做改动。立即生效，可恢复" } },
            { "set.nagle", new[]{ "TCP 低延迟（禁用 Nagle 合包与延迟 ACK）" } },
            { "set.netthrottle", new[]{ "网络限流值校正" } },
            { "set.netthrottle.n", new[]{ "把被改坏的网络限流值改回系统默认 10。改成「无限」是常见教程做法，实测反而抬高网络驱动延迟，而游戏流量根本碰不到那个上限。当前值正常时不做任何改动，重启生效" } },
            { "netthrottle.ok", new[]{ "当前值 {0}，在正常范围内，无需校正" } },
            { "netthrottle.broken", new[]{ "当前值 {0} 已超出有效范围，建议校正回系统默认 10" } },
            { "netthrottle.absent", new[]{ "当前未设置该值，即系统默认，无需校正" } },
            { "set.msi", new[]{ "启用 MSI 消息信号中断（显卡 / 网卡）" } },
            { "set.msi.n", new[]{ "让显卡和网卡用更快的中断方式，也不用再跟别的设备挤一条队。只动需要动的；硬盘和声卡有出问题的先例，一律不碰。重启生效，关掉即还原" } },
            { "msi.none", new[]{ "本机显卡与网卡均已启用 MSI，此项无事可做" } },
            { "set.devpower", new[]{ "禁止系统为省电关闭网卡" } },
            { "set.devpower.n", new[]{ "不让系统为省电给网卡断电。网卡被断电再唤醒会卡一下、掉包，笔记本无线网尤其明显。只改这一项，立即生效，可恢复" } },
            { "set.nagle.n", new[]{ "只对走 TCP 的游戏有用（MMO、回合制、Minecraft 这类），最多省小一百毫秒；MOBA / FPS 的对局流量用不上，完全没效果。新连接生效，可恢复" } },
            { "nagle.applied", new[]{ "已写入所有网卡，TCP 新建连接后生效；部分常驻在线的游戏需要重启游戏才会重新建连。" } },
            { "set.mpo", new[]{ "禁用多平面叠加（MPO）" } },
            { "set.mpo.n", new[]{ "画面闪烁、G-Sync 卡顿时可以关它试试；机器正常就别动，关了反而略亏。重启生效，可恢复" } },
            { "mpo.reboot", new[]{ "MPO 设置已修改，重启或重新登录后生效。" } },
            { "tame.lvl.eco", new[]{ "温和" } },
            { "tame.lvl.res", new[]{ "均衡" } },
            { "tame.lvl.iso", new[]{ "隔离" } },

            { "gs.moff", new[]{ "总开关关闭" } },
            { "gs.noff", new[]{ "未开启" } },
            { "gs.noproc", new[]{ "未检测到进程" } },
            { "gs.thr", new[]{ "已压制 {0}" } },
            { "gs.prot", new[]{ "（{0} 个受内核保护压不动）" } },

            { "white.desc", new[]{ "白名单里的程序永远不会被压制。「应用家族」保护这个程序和它开出来的子进程，但不放开整个目录；加上立刻生效。" } },
            { "white.scope", new[]{ "新增规则类型" } },
            { "white.page.sub", new[]{ "这里列出的程序永远不会被压制。把 EXE 或快捷方式拖进来就行，作用范围自动判断。" } },
            { "white.page.empty", new[]{ "白名单是空的\r\n把程序拖进来，或点右边「选运行中的程序」" } },
            { "white.page.pick", new[]{ "选运行中的程序" } },
            { "white.page.drop", new[]{ "把 EXE 或快捷方式直接拖进左边就能加。\r\n\r\n普通程序会连它拉起的子进程一起保护；命令行、脚本宿主这类只保护它自己——这个规则自动判断，不用你选。\r\n\r\n想改范围就右键条目。" } },
            { "white.page.platforms", new[]{ "这些游戏平台的客户端已经内置豁免，不用手动加：{0}。" } },
            { "white.badge.family", new[]{ "连子进程" } },
            { "white.badge.only", new[]{ "仅此程序" } },
            { "white.badge.name", new[]{ "按进程名" } },
            { "white.badge.name.sub", new[]{ "同名进程都算，不看路径" } },
            { "white.state.running", new[]{ "{0} 个在跑" } },
            { "white.state.idle", new[]{ "没在跑" } },
            { "white.menu.narrow", new[]{ "只保护这一个（不含子进程）" } },
            { "white.menu.widen", new[]{ "连子进程一起保护" } },
            { "white.required.locked", new[]{ "这是系统必需的内置项，不能删。" } },
            { "white.group.builtin", new[]{ "系统内置 · {0} 项 · 不可删" } },
            { "white.browse.filter", new[]{ "程序或快捷方式|*.exe;*.lnk|程序|*.exe|快捷方式|*.lnk" } },
            { "white.pick.title", new[]{ "选运行中的程序" } },
            { "white.pick.sub", new[]{ "只列出你自己开着的、有窗口的程序。系统进程和反作弊不在其中。" } },
            { "white.pick.busy", new[]{ "正在看有哪些程序开着…" } },
            { "white.pick.none", new[]{ "没有可加的程序——开着的都已经在白名单里了" } },
            { "white.pick.count", new[]{ "找到 {0} 个可加的程序" } },
            { "white.pick.add", new[]{ "加入白名单" } },
            { "white.pick.add.n", new[]{ "加入 {0} 个" } },
            { "white.pick.procs", new[]{ "{0} 进程" } },
            { "white.kind.family", new[]{ "应用家族" } },
            { "white.kind.family.recommended", new[]{ "应用家族（推荐）" } },
            { "white.kind.path", new[]{ "精确 EXE 路径" } },
            { "white.kind.name", new[]{ "进程名" } },
            { "white.kind.name.compat", new[]{ "进程名（兼容 / 宽泛）" } },
            { "white.matches", new[]{ "当前匹配 {0} 个" } },
            { "white.matches.pending", new[]{ "正在核对当前匹配…" } },
            { "white.path.required", new[]{ "这种规则需要完整的 EXE 路径。请用「浏览」选文件，或改用进程名规则。" } },
            { "white.duplicate", new[]{ "该规则已存在，或输入不是有效的 EXE / 进程名。" } },
            { "white.save.failed", new[]{ "白名单未能安全写入磁盘，本次修改未生效。请检查数据目录权限或磁盘状态。" } },
            { "white.required", new[]{ "Windows 稳定运行必需的内置保护，删不得；它只认受信的系统路径。" } },
            { "white.required.badge", new[]{ "内置保护" } },
            { "white.shortcut.invalid", new[]{ "无法解析该快捷方式的真实目标。请直接选择目标 EXE，避免保存无效或过宽的规则。" } },
            { "white.family.unsafe", new[]{ "这个目标是系统外壳或脚本宿主（或快捷方式带了参数），按家族放行会把别的程序一起放过去。请改用「精确 EXE 路径」，或直接选应用自己的 EXE。" } },
            { "white.reset.confirm", new[]{ "恢复默认预设会删除全部自定义白名单规则，且无法撤销。确定继续吗？" } },
            { "btn.reset", new[]{ "恢复默认预设" } },

            { "btn.openlog", new[]{ "打开日志文件" } },

            { "set.gpu", new[]{ "逐游戏高性能 GPU 偏好" } },
            { "set.gpu.n", new[]{ "双显卡笔记本强制走独显，下次启动游戏生效。" } },
            { "set.dvr", new[]{ "关闭 Game DVR / Xbox 后台录制" } },
            { "set.fso", new[]{ "逐游戏关闭全屏优化 (FSO)" } },
            { "set.fso.n", new[]{ "部分游戏降输入延迟，因游戏而异，可以试。" } },
            { "set.notif", new[]{ "游戏时免打扰" } },
            { "set.trim", new[]{ "自定义重压时清空后台占用的内存（可能触发读盘）" } },
            { "set.hz", new[]{ "刷新率守护（切到最高刷新率）" } },
            { "set.plan", new[]{ "游戏时切换电源计划" } },
            { "gm.gpudemote", new[]{ "后台 GPU 让位" } },
            { "gm.gpudemote.sub", new[]{ "被重压的后台用显卡时给游戏让路。要开直播、录屏请先把它们加白名单" } },
            { "gm.freeze", new[]{ "冻结静默后台" } },
            { "gm.freeze.sub", new[]{ "把已经压到最低、连续 30 秒没动静又没有任何窗口的后台彻底暂停，一点资源不占。被冻的程序完全停摆，收不到消息也存不了东西。仅竞技 / 激进自定义档生效" } },
            { "gm.freeze.warn", new[]{ "开启后台冻结？\r\n\r\n被冻住的程序会完全停摆：收不到消息、存不了东西、关机时也不响应。聊天软件会掉线，下载和云同步会断。\r\n\r\n同时满足这些条件才会被冻：竞技或激进自定义档、已被隔离压制、连续 30 秒没动静、没有任何窗口（最小化也算有窗口）、不在前台。反作弊、游戏、白名单、C:\\Windows 里的程序、别的账户，永远不会被冻。输入法、外设驱动这类怕卡的常驻程序不受自动保护，请自己加白名单。\r\n\r\n退出游戏、一键恢复、关掉本开关都会立刻解冻；就算 Caelus 崩了，下次启动也会把它们叫醒。只有托盘图标的程序被冻时点不动，用一键恢复即可。\r\n\r\n继续吗？" } },
            { "gm.boost", new[]{ "游戏提优（优先级 / 核心 / 读写 / 显卡全面偏向游戏）" } },
            { "gm.lane", new[]{ "保帧线程（单独抬高决定帧数的那个线程）" } },
            { "gm.lane.sub", new[]{ "游戏有上百个线程，真正决定帧数的往往就一个。开局认出它、单独再抬一档，游戏内部再怎么抢也先保出画面——加载、编译着色器时的卡顿会轻一些。认不出来就不动" } },
            { "gm.ifeo", new[]{ "后备提优（游戏被反作弊罩住时用）" } },
            { "gm.ifeo.sub", new[]{ "有的游戏被反作弊保护着，Caelus 碰不到它的进程，就改让 Windows 在进程创建那一刻直接给高优先级。只写优先级这一项，不碰调试劫持相关的键；下次启动游戏生效，关掉本开关即清除" } },
            { "gm.aggressive", new[]{ "竞技级压制范围" } },
            { "gm.aggressive.sub", new[]{ "开了就和竞技模式一样狠：开着窗口的程序（浏览器 / 语音 / IDE）也照压，只有你正在用的前台程序和它的子进程不动。游戏、反作弊、加速器、白名单和系统核心永远安全；C:\\Windows 里的只降速、绝不冻结。输入法、外设驱动这类怕卡的请自己加白名单。竞技模式必开；只有自定义可选，默认关" } },
            { "gm.pausedl", new[]{ "暂停后台下载（Windows 更新 / 传递优化）" } },
            { "gm.pausesvc", new[]{ "暂停索引 / 预取服务（机械盘收益明显）" } },
            { "set.autostart", new[]{ "开机自启" } },
            { "set.autostart.n", new[]{ "用管理员计划任务实现，开机不弹确认框。" } },
            { "set.autohide", new[]{ "检测到游戏后自动收起窗口" } },
            { "set.autohide.n", new[]{ "检测到游戏 10 秒后，窗口自动缩回托盘。每局只收一次，之后你再打开就不会又被收走。" } },
            { "set.hint", new[]{ "只有应用自己的偏好和维护工具在这里；显卡相关在「显卡」，改动系统的开关在「系统环境」。" } },
            { "sec.pergame", new[]{ "逐游戏 · 对局开始时下发，结束后还原" } },
            { "sec.app", new[]{ "应用自身" } },
            { "sec.maint", new[]{ "维护" } },
            { "nav.graphics", new[]{ "显卡" } },
            { "nav.env", new[]{ "系统环境" } },
            { "nav.audit", new[]{ "系统体检" } },
            { "nav.hardware", new[]{ "硬件与系统" } },
            { "audit.sub", new[]{ "只查不改：看这台机器什么能用、什么已经开了" } },
            { "audit.start", new[]{ "开始体检" } },
            { "audit.idle.title", new[]{ "还没有体检结果" } },
            { "audit.idle.hint", new[]{ "检测约需 4 秒，期间只读取不改动任何设置" } },
            { "audit.phase.capability", new[]{ "正在读取本机写入能力…" } },
            { "audit.phase.measure", new[]{ "正在实测中断分布与整机负载…" } },
            { "audit.phase.persistent", new[]{ "正在读取持久系统设置…" } },
            { "audit.phase.verdict", new[]{ "正在汇总结论…" } },
            { "audit.phase.done", new[]{ "完成" } },
            { "audit.nv.summary", new[]{ "{0}/{1} 项写入生效" } },
            { "audit.rerun", new[]{ "重新体检（3 秒）" } },
            { "audit.precise", new[]{ "精确测量（30 秒）" } },
            { "audit.nvprobe", new[]{ "NVIDIA 写入实测" } },
            { "audit.amdprobe", new[]{ "AMD 写入实测" } },
            { "audit.amd.unavailable", new[]{ "本机无 AMD ADLX 接口" } },
            { "audit.amd.failed", new[]{ "AMD 写入实测失败" } },
            { "audit.measuring", new[]{ "测量中（约 3 秒）…" } },
            { "audit.measuring.long", new[]{ "精确测量中（30 秒，期间请正常使用电脑）…" } },
            { "audit.failed", new[]{ "体检失败，接口不可用" } },
            { "audit.nv.probing", new[]{ "正在实际写一个测试值再读回来核对…" } },
            { "audit.nv.unavailable", new[]{ "本机无 NVIDIA 驱动接口" } },
            { "audit.nv.failed", new[]{ "写入实测失败" } },
            { "audit.nv.result", new[]{ "写入实测：" } },
            { "audit.sec.capability", new[]{ "写入能力 · 这些功能在本机能不能用" } },
            { "audit.sec.machine", new[]{ "本机实测 · 这台机器的实际情况" } },
            { "audit.sec.persistent", new[]{ "持久系统设置 · 重启生效，卸载后保留" } },
            { "audit.sec.verdicts", new[]{ "结论清单 · 每条都标注依据" } },
            { "audit.evidence", new[]{ "依据：" } },
            { "audit.footer", new[]{ "依据等级：本机实测＝在这台机器上测过；台架实测＝合成负载配对实验；机制明确＝原理清楚但没有量化数据；未验证＝没有测过。" } },
            { "v16.graphics.sub", new[]{ "显卡相关的开关。逐游戏的项只在打游戏时生效，退出自动还原。" } },
            { "v16.env.sub", new[]{ "这一页动的是系统底层，都要重启才生效；卸载 Caelus 也不会自动改回来，想恢复请先在这里关掉。" } },
            { "v17.log.sub", new[]{ "最近 220 行，切到本页自动刷新。每局结束的时长、压制数量和成效也记在这里。" } },
            { "sec.graphics.present", new[]{ "呈现路径 · 全局生效" } },
            { "sec.env.kernel", new[]{ "内核与驱动 · 需重启，改动不随 Caelus 卸载消失" } },
            { "btn.open", new[]{ "打开" } },
            { "btn.clean", new[]{ "清理" } },
            { "set.about", new[]{ "Caelus {0} · {1} · 本地配置与用户白名单" } },

            { "set.hags", new[]{ "开启 GPU 硬件调度 HAGS（需重启）" } },
            { "set.hags.n", new[]{ "切换 Windows 的 GPU 硬件调度。效果因显卡和游戏而异，有的帧生成功能必须开它。重启生效。" } },
            { "hags.reboot", new[]{ "已写入 HAGS 设置，重启电脑后生效。" } },
            { "set.irqaffinity", new[]{ "GPU 中断亲和优化（需重启设备或电脑）" } },
            { "set.irqaffinity.n", new[]{ "让显卡的中断信号走游戏核心附近，少绕路。重启生效。" } },
            { "irqaffinity.reboot", new[]{ "已写入中断亲和设置，重启该设备或重启电脑后生效。" } },
            { "set.netaffinity", new[]{ "游戏网络优先（需重启网卡或电脑）" } },
            { "set.netaffinity.n", new[]{ "网卡中断靠近游戏核心，游戏流量优先发，少排队、少抖动。重启生效。" } },
            { "netaffinity.reboot", new[]{ "网卡中断设置需要重启该网卡或重启电脑后生效；流量优先级标记会在新建立的网络连接上生效。" } },
            { "set.vbs", new[]{ "关闭 VBS + 停用 hypervisor（需重启）" } },
            { "vbs.state.on", new[]{ "当前：VBS 开着。关闭会降低安全性，帧数变化因机器而异，请自己对比" } },
            { "vbs.state.off", new[]{ "当前：VBS 未运行（本机已经没有这项开销）" } },
            { "vbs.state.pending", new[]{ "已设为关闭，重启电脑后生效" } },
            { "vbs.state.unknown", new[]{ "当前状态未知（无法查询 WMI）" } },
            { "vbs.warn", new[]{ "关闭 VBS / 内存完整性，并停掉虚拟化底层。\r\n\r\n系统安全性会下降，WSL2 / Docker / Hyper-V 虚拟机 / Windows 沙盒会用不了。帧数有没有提升因机器而异，没有普适结论，请自己前后对比。\r\n\r\n重启后生效；将来恢复也要再重启一次。\r\n\r\n继续吗？" } },
            { "vbs.needadmin", new[]{ "修改 VBS / hypervisor 需要管理员权限，请以管理员身份运行 Caelus。" } },
            { "vbs.done", new[]{ "已关闭 VBS 并停用 hypervisor。\r\n请重启电脑生效。重启后 WSL2 / Docker / Hyper-V / 沙盒将无法使用；要恢复请回到这里关掉此开关再重启。" } },
            { "vbs.restored", new[]{ "已恢复 VBS 与 hypervisor（hypervisorlaunchtype → 原值）。\r\n请重启电脑生效，之后 WSL2 / Docker 等恢复可用。" } },
            { "vbs.restorefail", new[]{ "还原未完全成功（bcdedit 可能失败），原状态快照已保留，可再试一次。详见日志。" } },

            { "btn.shader", new[]{ "清理着色器缓存" } },
            { "set.shader.n", new[]{ "怀疑缓存坏了可以清一次；清完游戏要重新编译，前几次进游戏可能更卡。" } },
            { "shader.busy", new[]{ "正在清理…" } },
            { "shader.confirm", new[]{ "清空显卡着色器缓存（NVIDIA / AMD / Intel / DirectX）？\r\n\r\n怀疑驱动更新后缓存坏了，可以清一次排查；不保证清完就流畅。\r\n\r\n清理前先退出游戏。之后每个游戏首次启动要重新编译，开头可能更卡。\r\n\r\n继续吗？" } },
            { "shader.freed", new[]{ "已清理着色器缓存，释放 {0}。" } },
            { "shader.skip", new[]{ "{0} 个文件正被占用已跳过（关闭游戏后可再清一次）。" } },
            { "shader.note", new[]{ "每个游戏下次启动都可能重新编译着色器，首次运行可能出现额外卡顿。" } },

            { "tray.aclist", new[]{ "反作弊列表" } },
            { "tray.reset", new[]{ "恢复默认配置" } },
            { "tray.resetask", new[]{ "把所有开关、反作弊选择和白名单恢复为默认？（游戏列表保留）" } },
            { "tm.gpu", new[]{ "高性能 GPU 偏好" } },
            { "tm.dvr", new[]{ "关闭 Game DVR" } },
            { "tm.fso", new[]{ "关闭全屏优化" } },
            { "tm.notif", new[]{ "游戏时免打扰" } },
            { "tm.trim", new[]{ "压制时清空后台内存" } },
            { "tm.plan", new[]{ "游戏时切换电源计划" } },
            { "tm.autostart", new[]{ "开机自启" } },

            { "about.desc", new[]{ "把系统资源让给当前重任的 Windows 工具——打游戏、写代码、编译，都需要专注算力。\r\n无第三方依赖 · 改过的都能恢复" } },
            { "about.author", new[]{ "作者" } },
            { "about.repo", new[]{ "源码仓库" } },
            { "about.lic", new[]{ "许可协议" } },
            { "about.lic.value", new[]{ "Caelus 许可协议 · 禁止销售" } },
            { "about.wechat", new[]{ "微信" } },
            { "btn.checkupd", new[]{ "检查更新" } },
            { "btn.download", new[]{ "前往下载" } },
            { "upd.checking", new[]{ "正在检查更新…" } },
            { "upd.latest", new[]{ "已是最新版本（{0}）" } },
            { "upd.newver", new[]{ "发现新版本 {0}（当前 {1}），点击「前往下载」获取。" } },
            { "upd.fail", new[]{ "检查更新失败：网络不可用或仓库暂未发布版本。" } },
            { "bal.update", new[]{ "发现新版本 {0}，请打开面板「关于」页查看。" } },

            { "dlg.pickproc", new[]{ "选择进程" } },
            { "btn.add", new[]{ "添加" } },
            { "btn.cancel", new[]{ "取消" } },
            { "dlg.bgsvc", new[]{ "[后台服务]" } },
            { "ofd.game", new[]{ "选择游戏 EXE 或 Windows 快捷方式" } },
            { "ofd.white", new[]{ "选择要加入白名单的 exe" } },
            { "ofd.filter", new[]{ "游戏程序或快捷方式 (*.exe;*.lnk;*.url)|*.exe;*.lnk;*.url|程序 (*.exe)|*.exe|快捷方式 (*.lnk;*.url)|*.lnk;*.url" } },
            { "pick.busy", new[]{ "正在统计资源占用…" } },
            { "pick.count", new[]{ "共 {0} 个可执行程序 · 同路径实例合并显示" } },
            { "msg.taskfail", new[]{ "计划任务操作失败（需要管理员权限运行 Caelus）" } },

            { "tray.open", new[]{ "打开面板" } },
            { "btn.panic", new[]{ "一键恢复已记录项" } },
            { "tray.exit", new[]{ "退出" } },
            { "tray.active", new[]{ "Caelus - 守护中（{0}）" } },
            { "tray.idle", new[]{ "Caelus - 待命，未检测到游戏" } },
            { "tray.armed", new[]{ "Caelus - 已就位《{0}》，进对局自动接管" } },
            { "tray.noelev", new[]{ "Caelus - 未提权！压制类功能无效" } },
            { "bal.noelev", new[]{ "当前未以管理员运行，压制类功能不会生效。" } },
            { "bal.buildstart", new[]{ "编译优化中：后台已降级，编译器优先拿资源" } },
            { "bal.buildend", new[]{ "编译结束，已恢复后台资源" } },
            { "set.dev", new[]{ "开发模式" } },
            { "set.dev.n", new[]{ "检测到编译/调试进程（msbuild、gcc、npm 等）时自动压制后台，编译完恢复" } },
            { "panic.done", new[]{ "能确认的改动都已还原，电源和调度交还给系统。\r\n游戏还开着的话，几秒后会重新接管；想彻底停用，请关掉游戏模式和反作弊压制。" } },
            { "panic.timeout", new[]{ "还有一部分没确认还原完，Caelus 会继续自动重试。想彻底停用，请关掉游戏模式和反作弊压制。" } },
            { "panic.failedcount", new[]{ "未确认完成：{0}/{1} 项" } },
            { "rep.done", new[]{ "{0} 本局 {1}，压制 {2} 个后台进程，期间它们合计只用了 {3} CPU" } },
            { "rep.top", new[]{ "，占用最高 {0}（{1}）" } },
            { "rep.caelus.cpu", new[]{ "；Caelus 主进程平均 CPU {0}%" } },
            { "rep.gputhrottle", new[]{ "；显卡这局被什么拖了后腿：{0}" } },


            { "lolq.err.noinput", new[]{ "未提供英雄联盟目录" } },
            { "lolq.err.badformat", new[]{ "英雄联盟目录格式无效" } },
            { "lolq.err.notroot", new[]{ "目录不是有效的国服英雄联盟安装根目录" } },
            { "lolq.err.enumproc", new[]{ "无法枚举系统进程" } },
            { "lolq.proc.unknown", new[]{ "未知进程" } },
            { "lolq.err.clientrunning", new[]{ "检测到运行中的客户端：{0}" } },
            { "lolq.item.notdir", new[]{ "目标不是目录，未处理" } },
            { "lolq.item.vanished", new[]{ "源目录在执行前发生变化" } },
            { "lolq.err.srcreparse", new[]{ "目标路径包含重解析点" } },
            { "lolq.item.deleted", new[]{ "已删除" } },
            { "lolq.item.deletefail", new[]{ "删除失败：{0}" } },
            { "lolq.err.deleteincomplete", new[]{ "目录未能完全删除，可能仍被占用" } },
            { "lolq.msg.deldone", new[]{ "已删除英雄联盟附加层" } },
            { "lolq.msg.delpartial", new[]{ "删除只完成了一部分，请关闭占用后重试" } },
            { "lolq.msg.delnone", new[]{ "未删除任何内容" } },
            { "lolq.err.rootunresolved", new[]{ "安装目录形状暂时无法确认（客户端可能正在更新）" } },
            { "lolq.err.closefirst", new[]{ "请先关闭英雄联盟与 WeGame：{0}" } },
            { "lolq.err.nocandidate", new[]{ "没有检测到可删除的附加层目录" } },
            { "lolq.err.generic", new[]{ "操作失败" } },
            { "lolq.err.candnotdir", new[]{ "候选路径不是目录" } },
            { "lolq.err.candreparse", new[]{ "候选目录是重解析点" } },
            { "lolq.err.scanfail", new[]{ "无法完整扫描：{0}" } },
            { "lolq.err.filereparse", new[]{ "目录包含文件重解析点：{0}" } },
            { "lolq.err.readfile", new[]{ "无法读取文件信息：{0}" } },
            { "lolq.err.dirreparse", new[]{ "目录包含子目录重解析点：{0}" } },
            { "lolq.err.readdir", new[]{ "无法读取目录信息：{0}" } },
            { "lolq.err.outsideroot", new[]{ "路径超出英雄联盟目录" } },
            { "lolq.err.outsiderootr", new[]{ "目标路径超出英雄联盟目录" } },
            { "lolq.err.pathreparse", new[]{ "目标路径包含重解析点" } },
            { "lolq.err.pathinvalid", new[]{ "目标路径无效" } },

            { "ac.ace.n", new[]{ "ACE 反作弊专家 (腾讯)" } },
            { "ac.ace.d", new[]{ "英雄联盟国服 / 无畏契约国服 / 三角洲行动 / CF 等" } },
            { "ac.tp.n", new[]{ "TenProtect / TP (腾讯)" } },
            { "ac.tp.d", new[]{ "ACE 前身，穿越火线等老游戏仍在用" } },
            { "ac.vanguard.n", new[]{ "Vanguard (Riot)" } },
            { "ac.vanguard.d", new[]{ "无畏契约 / 英雄联盟 · vgk 为内核驱动无法压制" } },
            { "ac.eac.n", new[]{ "EasyAntiCheat (Epic)" } },
            { "ac.eac.d", new[]{ "俗称「小蓝熊」· Apex / 堡垒之夜 / 永劫无间 / 幻兽帕鲁 等" } },
            { "ac.battleye.n", new[]{ "BattlEye" } },
            { "ac.battleye.d", new[]{ "PUBG / 彩虹六号 / DayZ / 逃离塔科夫 · BEDaisy 为驱动" } },
            { "ac.eaac.n", new[]{ "EA Javelin (EA 反作弊)" } },
            { "ac.eaac.d", new[]{ "战地 2042 / 战地 6 / FC 等 EA 游戏 · 另有内核驱动" } },
            { "ac.gameguard.n", new[]{ "nProtect GameGuard" } },
            { "ac.gameguard.d", new[]{ "DNF 等部分韩系网游" } },
            { "ac.faceit.n", new[]{ "FACEIT 反作弊" } },
            { "ac.faceit.d", new[]{ "CS2 第三方竞技平台" } },
            { "ac.neac.n", new[]{ "NEAC 反作弊 (网易)" } },
            { "ac.neac.d", new[]{ "部分网易游戏 · 另有内核组件" } },
        };

        public static void Init()
        {
            Cur = 0;
        }

        public static void Set(int i)
        {
            Cur = 0;
            Settings.SaveStr("Lang", "zh");
        }

#if CAELUS_SELFTEST
        internal static List<string> AllKeys()
        {
            var keys = new List<string>();
            foreach (var kv in M) keys.Add(kv.Key);
            return keys;
        }

        internal static string[] Row(string key)
        {
            string[] a;
            return M.TryGetValue(key, out a) ? a : null;
        }
#endif

        public static string T(string key)
        {
            string[] a;
            if (M.TryGetValue(key, out a)) return a[Cur < a.Length ? Cur : 0];
            return key;
        }

        public static string F(string key, params object[] args) { return string.Format(T(key), args); }

        public static bool HasKey(string key) { return key != null && M.ContainsKey(key); }
    }

}
